site_name: Yet Another Analytic Dataflow Architecture
copyright: Aptima, Inc. 2023
site_dir: public
theme:
  name: material
nav:
    - Home: index.md
    - Getting Started: getting-started.md
    - Architecture and Concepts: concepts.md
    - Tutorial: tutorial.md
    - Python API: api.md
    - REST API: openapi.md
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - tables
plugins:
   - swagger-ui-tag
   - mkdocstrings
   - search