version: '3.6'

services:
  opensearch:
    ports:
      - "9200:9200"
  opensearch-dashboards:
    ports:
      - "5601:5601"
  zenko:
    ports:
      - "8000:8000"
  mosquitto:
    ports:
     - "1883:1883"
     - "9001:9001"
{% if cookiecutter.include_tika == 'y' %}
  tika:
    ports:
      - "9998:9998"
{% endif %}