# ARG PLATFORM=amd64
FROM --platform=linux/amd64 zenko/cloudserver:latest-7.70.10
# ARG PLATFORM=amd64
# RUN echo "building for platform: linux/$PLATFORM"
COPY config/config.json /usr/src/app/config.json
