version: '3.6'
volumes:
  # shared_minio_volume:
  shared_zenko_data_volume:
  shared_zenko_metadata_volume:
  shared_opensearch_volume:
  shared_mosquitto_volume:

networks:
  default:
    name: ${YAADA_NETWORK_NAME:-yaada-shared-infrastructure}
    external: true
services:
  opensearch:
    image: opensearchproject/opensearch:1.3.7
    platform: linux/${DOCKER_PLATFORM}
    restart: always
    volumes:
      - shared_opensearch_volume:/usr/share/opensearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 15s
      timeout: 10s
      retries: 3
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true" # Prevents execution of bundled demo script which installs demo certificates and security configurations to OpenSearch
      - "DISABLE_SECURITY_PLUGIN=true" # Disables security plugin
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:1.3.7
    platform: linux/${DOCKER_PLATFORM}
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: true
    restart: always

  # If we need to change the name of the zenko container, we will need to update docker/zenko-cloudserver/config/config.json to make sure
  # there is a region mapping in the restEndpoints section for the new url.
  # See https://stackoverflow.com/questions/49339557/connecting-to-scality-s3-server-between-docker-containers.
  zenko: 
    image: yaada/zenko-cloudserver:${PROJECT_IMAGE_TAG}
    platform: linux/amd64
    restart: always
    environment:
      S3BACKEND: file
      REMOTE_MANAGEMENT_DISABLE: 1
      SCALITY_ACCESS_KEY_ID: AptimaKey
      SCALITY_SECRET_ACCESS_KEY: AptimaSecret
      SSL: "FALSE"
      LISTEN_ADDR: 0.0.0.0
    volumes:
      - shared_zenko_data_volume:/usr/src/app/localData
      - shared_zenko_metadata_volume:/usr/src/app/localMetadata
  mosquitto:
    image: yaada/mosquitto:${PROJECT_IMAGE_TAG}
    platform: linux/${DOCKER_PLATFORM}
    restart: always
    volumes:
      - "shared_mosquitto_volume:/mosquitto/data"
  tika: # see https://github.com/LogicalSpark/docker-tikaserver
    image: logicalspark/docker-tikaserver
    restart: always
